# Author:  James Buckett
# eMail: james.buckett@gmail.com
# Loki values for Helm install

loki:
  enabled: true
  image:
    tag: 2.0.0

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true
  # Deploy default dashboards. These are loaded using the sidecar
  defaultDashboardsEnabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 7.3.1
  service:
    type: LoadBalancer
  
prometheus:
  enabled: true
  alertmanager.persistentVolume.enabled: false
  server.persistentVolume.enabled: false
  image:
    tag: 2.22.0