# Author:  James Buckett
# eMail: james.buckett@gmail.com
# Loki values for Helm install

loki:
  enabled: true
  image:
    tag: 2.2.0

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true
  # Deploy default dashboards. These are loaded using the sidecar
  defaultDashboardsEnabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 7.5.2
  service:
### Contour Testing ###
### Added line below from type: LoadBalancer to ClusterIP
    #type: LoadBalancer    
    type: ClusterIP
  
prometheus:
  enabled: true
  alertmanager.persistentVolume.enabled: false
  server.persistentVolume.enabled: false
  image:
    tag: 2.25.2