apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpbin
spec:
  rules:
  - host: frontend.jamesbuckett.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80