apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-argo
  namespace: ns-argo
spec:
  rules:
  - host: argo.jamesbuckett.com
    http:
      paths:
      - backend:
          serviceName: argo-server
          servicePort: 2746