apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-demo
  namespace: ns-microservices-demo
spec:
  rules:
  - host: demo.jamesbuckett.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80