apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-chaos-mesh
  namespace: ns-chaos-mesh
spec:
  rules:
  - host: chaosmesh.jamesbuckett.com
    http:
      paths:
      - backend:
          serviceName: chaos-dashboard
          servicePort: 2333
