apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-argo
  namespace: ns-argo
  annotations:
    ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: argo.jamesbuckett.com
    http:
      paths:
      - backend:
          serviceName: argo-server
          servicePort: 2746
        path: /argo(/|$)(.*)