apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-vpa
  namespace: ns-vpa
spec:
  rules:
  - host: goldilocks.jamesbuckett.com
    http:
      paths:
      - backend:
          service.name: goldilocks-release-dashboard
          service.port.number: 80