apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-istio
  namespace: istio-system
spec:
  rules:
    - host: kiali.jamesbuckett.com
      http:
        paths:
          - backend:
              serviceName: kiali
              servicePort: 20001
