apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: rewrite
  namespace: ns-nginx
spec:
  rules:
  - host: demo.jamesbuckett.com
    http:
      paths:
      - path: /frontend
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /service-2
        backend:
          serviceName: service-2
          servicePort: 5000
      - path: /service-2
        backend:
          serviceName: service-2
          servicePort: 5000
      - path: /service-2
        backend:
          serviceName: service-2
          servicePort: 5000          

